
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


 
/**
 * 识别类型
 */
export enum IdentifyType {
    /**
     * 图像
     */
    IMAGE = 0,
    /**
     * 文本
     */
    TEXT = 1,
}

 
 
/**
 * 节点引脚类型
 */
export enum NodePinType {
    /**
     * 文本
     */
    STRING = 0,
    /**
     * 数值
     */
    NUMBER = 1,
    /**
     * 游戏模块
     */
    GAME_MODULE = 2,
    /**
     * 游戏按钮
     */
    GAME_BUTTON = 3,
    /**
     * 自动游戏按钮
     */
    AUTO_GAME_BUTTON = 4,
    /**
     * 游戏副本
     */
    GAME_CAMPAIGN = 5,
}

 





export class AutoGameButton {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.description === undefined) { throw new Error() }
        this.description = _json_.description
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly description: string

    resolve(tables:Tables) {
        
        
        
    }
}





export class GameButton {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.full_name === undefined) { throw new Error() }
        this.fullName = _json_.full_name
        if (_json_.correspond_auto_control_name === undefined) { throw new Error() }
        this.correspondAutoControlName = _json_.correspond_auto_control_name
        if (_json_.identify_type === undefined) { throw new Error() }
        this.identifyType = _json_.identify_type
        if (_json_.identify_asset === undefined) { throw new Error() }
        this.identifyAsset = _json_.identify_asset
        if (_json_.identify_threshold === undefined) { throw new Error() }
        this.identifyThreshold = _json_.identify_threshold
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 全名称（路径+名称）
     */
    readonly fullName: string
    /**
     * 对应的自动游戏按钮名称
     */
    readonly correspondAutoControlName: string
    /**
     * 识别类型
     */
    readonly identifyType: IdentifyType
    /**
     * 识别资源（图片或文本）
     */
    readonly identifyAsset: string
    /**
     * 识别阈值
     */
    readonly identifyThreshold: number

    resolve(tables:Tables) {
        
        
        
        
        
        
    }
}





export class GameCampaign {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.game_module === undefined) { throw new Error() }
        this.gameModule = _json_.game_module
        if (_json_.identify_type === undefined) { throw new Error() }
        this.identifyType = _json_.identify_type
        if (_json_.identify_asset === undefined) { throw new Error() }
        this.identifyAsset = _json_.identify_asset
        if (_json_.identify_threshold === undefined) { throw new Error() }
        this.identifyThreshold = _json_.identify_threshold
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 副本名称
     */
    readonly name: string
    /**
     * 所属游戏模块
     */
    readonly gameModule: string
    /**
     * 识别类型
     */
    readonly identifyType: IdentifyType
    /**
     * 识别资源（图片或文本）
     */
    readonly identifyAsset: string
    /**
     * 识别阈值
     */
    readonly identifyThreshold: number

    resolve(tables:Tables) {
        
        
        
        
        
        
    }
}





export class GameModule {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.full_name === undefined) { throw new Error() }
        this.fullName = _json_.full_name
        if (_json_.identify_type === undefined) { throw new Error() }
        this.identifyType = _json_.identify_type
        if (_json_.identify_asset === undefined) { throw new Error() }
        this.identifyAsset = _json_.identify_asset
        if (_json_.identify_threshold === undefined) { throw new Error() }
        this.identifyThreshold = _json_.identify_threshold
        if (_json_.description === undefined) { throw new Error() }
        this.description = _json_.description
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 全名称（路径+名称）
     */
    readonly fullName: string
    /**
     * 识别类型
     */
    readonly identifyType: IdentifyType
    /**
     * 识别资源（图片或文本）
     */
    readonly identifyAsset: string
    /**
     * 识别阈值
     */
    readonly identifyThreshold: number
    /**
     * 描述
     */
    readonly description: string

    resolve(tables:Tables) {
        
        
        
        
        
        
    }
}





export class Node {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.catalogue === undefined) { throw new Error() }
        this.catalogue = _json_.catalogue
        if(_json_.pin0 != undefined) { this.pin0 = new NodePin(_json_.pin0) } else { this.pin0 = undefined }
        if(_json_.pin1 != undefined) { this.pin1 = new NodePin(_json_.pin1) } else { this.pin1 = undefined }
        if(_json_.pin2 != undefined) { this.pin2 = new NodePin(_json_.pin2) } else { this.pin2 = undefined }
        if(_json_.pin3 != undefined) { this.pin3 = new NodePin(_json_.pin3) } else { this.pin3 = undefined }
        if (_json_.description === undefined) { throw new Error() }
        this.description = _json_.description
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 目录
     */
    readonly catalogue: string
    /**
     * 引脚0-类型
     */
    readonly pin0: NodePin|undefined
    /**
     * 引脚1-类型
     */
    readonly pin1: NodePin|undefined
    /**
     * 引脚2-类型
     */
    readonly pin2: NodePin|undefined
    /**
     * 引脚3-类型
     */
    readonly pin3: NodePin|undefined
    /**
     * 描述
     */
    readonly description: string

    resolve(tables:Tables) {
        
        
        
        this.pin0?.resolve(tables);
        this.pin1?.resolve(tables);
        this.pin2?.resolve(tables);
        this.pin3?.resolve(tables);
        
    }
}





export class NodePin {

    constructor(_json_: any) {
        if (_json_.type === undefined) { throw new Error() }
        this.type = _json_.type
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
    }

    /**
     * 引脚类型
     */
    readonly type: NodePinType
    /**
     * 引脚名称
     */
    readonly name: string

    resolve(tables:Tables) {
        
        
    }
}






export class TbGameModule {
    private _dataMap: Map<number, GameModule>
    private _dataList: GameModule[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, GameModule>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: GameModule
            _v = new GameModule(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, GameModule> { return this._dataMap; }
    getDataList(): GameModule[] { return this._dataList; }

    get(key: number): GameModule | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbNode {
    private _dataMap: Map<number, Node>
    private _dataList: Node[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, Node>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: Node
            _v = new Node(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, Node> { return this._dataMap; }
    getDataList(): Node[] { return this._dataList; }

    get(key: number): Node | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbGameCampaign {
    private _dataMap: Map<number, GameCampaign>
    private _dataList: GameCampaign[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, GameCampaign>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: GameCampaign
            _v = new GameCampaign(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, GameCampaign> { return this._dataMap; }
    getDataList(): GameCampaign[] { return this._dataList; }

    get(key: number): GameCampaign | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbGameButton {
    private _dataMap: Map<number, GameButton>
    private _dataList: GameButton[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, GameButton>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: GameButton
            _v = new GameButton(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, GameButton> { return this._dataMap; }
    getDataList(): GameButton[] { return this._dataList; }

    get(key: number): GameButton | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbAutoGameButton {
    private _dataMap: Map<number, AutoGameButton>
    private _dataList: AutoGameButton[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, AutoGameButton>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: AutoGameButton
            _v = new AutoGameButton(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, AutoGameButton> { return this._dataMap; }
    getDataList(): AutoGameButton[] { return this._dataList; }

    get(key: number): AutoGameButton | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




type JsonLoader = (file: string) => any

export class Tables {
    private _TbGameModule: TbGameModule
    get TbGameModule(): TbGameModule  { return this._TbGameModule;}
    private _TbNode: TbNode
    get TbNode(): TbNode  { return this._TbNode;}
    private _TbGameCampaign: TbGameCampaign
    get TbGameCampaign(): TbGameCampaign  { return this._TbGameCampaign;}
    private _TbGameButton: TbGameButton
    get TbGameButton(): TbGameButton  { return this._TbGameButton;}
    private _TbAutoGameButton: TbAutoGameButton
    get TbAutoGameButton(): TbAutoGameButton  { return this._TbAutoGameButton;}

    constructor(loader: JsonLoader) {
        this._TbGameModule = new TbGameModule(loader('tbgamemodule'))
        this._TbNode = new TbNode(loader('tbnode'))
        this._TbGameCampaign = new TbGameCampaign(loader('tbgamecampaign'))
        this._TbGameButton = new TbGameButton(loader('tbgamebutton'))
        this._TbAutoGameButton = new TbAutoGameButton(loader('tbautogamebutton'))

        this._TbGameModule.resolve(this)
        this._TbNode.resolve(this)
        this._TbGameCampaign.resolve(this)
        this._TbGameButton.resolve(this)
        this._TbAutoGameButton.resolve(this)
    }
}

